Handle traps

diff --git a/run-tests b/run-tests
--- a/run-tests
+++ b/run-tests
@@ -10,6 +10,14 @@ packetdrill=/usr/home/zeebsd/packetdrill/gtests/net/packetdrill/packetdrill
 directory="$1"
 extension=".pkt"
 
+trap clean_up SIGHUP SIGINT SIGTERM
+
+clean_up() {
+  echo "Cleaning up"
+  rm -f temp_list temp.log
+  exit 1
+}
+
 file=tests_list   # contains the list of ".pkt" files in case the argument is empty or a directory
 pkt_file_flag=0   # tracks whether the argument is a ".pkt" file
 
@@ -22,7 +30,7 @@ fi
 
 if [ ! -e $file ]
 then
-  `find . -type f -iname '*.pkt' | cut -f 2 -d '.' > tests_list`
+  find . -type f -iname '*.pkt' | cut -f 2 -d '.' > tests_list
 fi
 
 # Check if the argument is a ".pkt" file
@@ -34,7 +42,7 @@ fi
 # Check if the argument is a directory
 if [ ! -z "$directory" ] && [ $pkt_file_flag == 0 ]
 then
-  `find ./$directory -type f -iname '*.pkt' | cut -f 2 -d '.' > temp_list`
+  sh update-test-list
   file=temp_list
 fi
 
@@ -47,16 +55,15 @@ failed=0
 # Modify values depending on return status
 check_status() {
   run=`expr $run + 1`
-  if [ $result = 1 ]
+  if [ $result == 1 ]
   then
-    `printf "Test Name: ${test}\.pkt\n" >> error.log`
-    `printf "\---------------------------------------------------------\n" >> error.log`
-    `cat temp.log >> error.log`
-    `printf "\n" >> error.log`
+    printf "Test Name: ${test}\.pkt\n" >> error.log
+    printf "\---------------------------------------------------------\n" >> error.log
+    cat temp.log >> error.log
+    printf "\n" >> error.log
     echo -e "\e[0;31mFAILED\e[0m"
     printf "\--------------------------------------------------------------\n"
     failed=`expr $failed + 1`
-    # set -- "$@" $test
   else
     echo -e "\e[1;32mPASSED\e[0m"
     printf "\---------------------------------------------------------------\n"
@@ -64,7 +71,7 @@ check_status() {
   fi
 }
 
-`rm -f error.log`
+rm -f error.log
 printf "\nScript Name                                             Result\n"
 printf "===============================================================\n"
 
@@ -74,8 +81,8 @@ then
   printf "%-55.55s " $directory
   if [ -e $directory ]
   then
-    `rm -f temp.log`
-    `$packetdrill -v --tolerance_usecs=1000000 $directory >> temp.log 2>&1`
+    rm -f temp.log
+    $packetdrill -v --tolerance_usecs=1000000 $directory >> temp.log 2>&1
     result="`echo $?`"
     check_status
   else
@@ -87,21 +94,19 @@ else
   while IFS= read test
   do
     printf "%-55.55s " .$test
-    `sleep $delay`
+    sleep $delay
     if [ -e .${test}.pkt ]
     then
-      `rm -f temp.log`
-      `$packetdrill -v --tolerance_usecs=1000000 .${test}.pkt >> temp.log 2>&1`
+      rm -f temp.log
+      $packetdrill -v --tolerance_usecs=1000000 .${test}.pkt >> temp.log 2>&1
       result="`echo $?`"
       check_status
     else
-      printf "%-55.55s " .$test
       echo -e "\e[1;33mSKIPPED\e[0m"
       skipped=`expr $skipped + 1`
     fi
   done< "$file"
-  `rm -f temp.log`
-  `rm -f temp_list`
+  rm -f temp.log temp_list
 fi
 
 printf "\nSummary\n"
@@ -111,11 +116,8 @@ printf "Number of tests run: %6d\n" $run
 printf "Number of tests passed: %3d\n" $passed
 printf "Number of tests failed: %3d\n" $failed
 printf "Number of tests skipped: %2d\n" $skipped
+
 if [ $failed -ne 0 ]
 then
   printf "\nView the log file (error.log) for details\n"
 fi
-
-# printf "\nList of failed tests\n"
-# printf "===========================\n"
-# printf '%s\n' "$@"
